name: Terraform PR Plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # 🔥 necesario para OIDC
  contents: read
  pull-requests: write
  issues: write

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: dev  # Siempre previsualiza con un entorno tipo dev

    env:
      TF_ENV: dev  # Always preview with dev-like environment

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="vars/${{ env.TF_ENV }}.tfvars" -out=tfplan

      - name: Convert Plan to Text
        run: terraform show -no-color tfplan